
try:
    f = open('fact.py')
    v = bad_var
except Exception:
    print("Some error occurred")



print("Done")